print ("hello this is my first time using python")
print ("my name is logan")
print ("i live in houston texas")
print ("my dream car is the 1969 boss 429 mustang")
print ("i am 15")
print (" in my opion John wick 1,2,4, Intestellar, The martian, are some of the best movies of all time")
print ("my dream collages/universitys are texas tech, A and M, MIT")
print (" im looking into a wide selection of jobs from engeneering, trade so i can work up to owning my own bussisness or anything computer dev related")
print ("this account is simply a way for me to track my progress and post my work for future refrance")